# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SkiApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SkiApp
  pod 'AppCenterReactNativeShared', '~> 1.0.1'

  

  target 'SkiAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SkiApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SkiApp-tvOS

  target 'SkiApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
